import java.io.*;
import java.util.*;
import java.text.*;
import static java.lang.Math.*;
public class temp{
    public static void main(String args[]){
        System.out.println("\nFunkcje występujące w C:acos, asin, atan, cbrt, ceil, floor, pow");
        double x;
        x=2.74;
        System.out.println("\nx=" + x + " abs(x)=" + abs(x) + "\nMetoda abs oblicza wartość bezwzględną zmiennej");
        int sil;
        sil=3*12*11*10*9*8*7*6*5*4*3*2*1;
        int sil2;
        sil2=3*12*11*10*9*8*7*6*5*4*3*2*1;
        System.out.println("\nx=" + sil + "y=" + sil2 + "\naddExact(x,y)=" + addExact(sil,sil2) + "\nMetoda addExact oblicza sumę zmiennych,");
        System.out.println("jednak gdy ta przekroczy ich zakres drukuje błąd");
        double y;
        y=-9;
        System.out.println("\nx="+ x + " y=" + y + " copySign(x,y)=" + copySign(x,y) + "\nMetoda copySign nadaje");
        System.out.println("pierwszej zmiennej znak drugiej zmiennej");
        sil=-2147483647;
        System.out.println("\nx=" + sil + "decrementExact(x)=" + decrementExact(sil) + "\nMetoda decrementExact odejmuje 1 od zmiennej,");
        System.out.println("jednak gdy ta przekroczy jej zakres drukuje błąd");
        x=3;
        System.out.println("\nx=" + x + " expm1(x)=" + expm1(x) + " exp(x)=" + exp(x));
        System.out.println("Metoda expm1 oblicza wartość e podniesionej");
        System.out.println("do potęgi zmiennej i zmniejsza wynik o 1");
        int z;
        z=1279;
        System.out.println("\nx=" + z + " floorDiv(x,100)=" + floorDiv(z,100) + " floorDiv(x,1000)=" + floorDiv(z,1000));
        System.out.println("Metoda floorDiv zaokrągla zmienną do danej wartości");
        System.out.println("i wyświetla ilość wielokrotności tej wartości");
        System.out.println("\nx=" + z + " floormod(x,100)=" + floorMod(z,100) + " floorMod(x,1000)=" + floorMod(z,1000));
        System.out.println("Metoda floorMod dzieli zmienną przez daną wartość");
        System.out.println("i wyświetla resztę z dzielenia");
        x=256.74;
        System.out.println("\nx=" + x + " getExponent(x)=" + getExponent(x));
        System.out.println("Metoda getExponent oblicza największy wykładnik potęgi 2,");
        System.out.println("którego wynik jest mniejszy i najbliższy zmiennej");
        x=4;
        System.out.println("\nx="+ x + " y=" + y + " hypot(x,y)=" + hypot(x,y));
        System.out.println("\nMetoda hypot oblicza pierwiastek z wyrażenia (x^2+y^2)");
        System.out.println("\nx="+ x + " y=" + y + " IEEEremiander(x,y)=" + IEEEremainder(x,y));
        System.out.println("incrementExact zwraca argument zwiekszony o jeden, zglaszajac wyjatek,");
        System.out.println("jesli wynik przepelnia okreslony typ danych long lub int, w zaleznosci od tego, ktory typ danych zostal uzyty w argumencie metody.");
        System.out.println("Przed "+z+" Po: "+Math.incrementExact(z));
        System.out.println("max daje maksimum z dwoch argumentow. Argumentem moze byc int, float, long,double");
        System.out.println("Przed "+x+" i "+y+" Po: "+Math.max(x,y));
        System.out.println("min jest wbudowana funkcja Java, ktora zwraca co najmniej dwie liczby.");
        System.out.println("Przed "+x+" i "+y+" Po: "+Math.min(x,y));
        System.out.println("multiplyExact zwraca iloczyn argumentow.");
        int n;
        n=10;
        System.out.println("Przed "+z+" i "+n+" Po: "+Math.multiplyExact(z,n));
        System.out.println("negateExact zwraca negacje argumentu.");
        System.out.println("Przed "+z+" Po: "+Math.negateExact(z));
        System.out.println("nextDown");
        System.out.println("Przed "+z+" Po: "+Math.nextDown(z));
        System.out.println("nextUp zwraca wartosc zmiennoprzecinkowa sasiadujaca z podanym parametrem w kierunku dodatniej nieskonczonosci.");
        System.out.println("Przed "+z+" Po: "+Math.nextUp(z));
        System.out.println("nextAfter zwraca liczbe zmiennoprzecinkowa sasiadujaca z pierwszym argumentem w kierunku drugiego argumentu.");
        System.out.println("Przed "+x+" i "+y+" Po: "+Math.nextAfter(x,y));
        x=256.74;
        System.out.println("rint zwraca wartosc najblizsza podanej wartosci i jest rowna matematycznej liczbie calkowitej.");
        System.out.println("Przed "+x+" Po: "+Math.rint(x));
        x=4;
        System.out.println("scalb sluzy do uzyskania wartasci a x 2^ scale.");
        System.out.println("Przed "+z+" i "+n+" Po: "+Math.scalb(z,n));
        System.out.println("signum zwraca funkcje Sign wartosci przekazanej jako argument.");
        System.out.println("Przed "+y+" Po: "+Math.signum(y));
        System.out.println("subtractExact-zwraca roznice argumentow. Zglosi wyjatek, jesli wynik przekroczy wartosc int lub long.");
        System.out.println("Przed "+z+" i "+n+" Po: "+Math.subtractExact(z,n));
        System.out.println("toDegrees sluzy do konwersji kąta mierzonego w radianach na w przyblizeniu rownowazny kat mierzony w stopniach.");
        System.out.println("Przed "+x+" Po: "+Math.toDegrees(x));
        System.out.println("toIntExact zwraca wartosc długiego argumentu.");
        System.out.println("Przed "+z+" Po: "+Math.toIntExact(z));
        System.out.println("toRadians sluzy do konwersji kata mierzonego w stopniach na w przyblizeniu rownowazny kat mierzony w radianach. ");
        x=90;
        System.out.println("Przed "+x+" Po: "+Math.toRadians(x));
        System.out.println("ulp zwraca rozmiar ulp argumentu. Ulp oznacza jednostke o najmniejszej precyzji.");
        x=256.74;
        System.out.println("Przed "+x+" Po: "+Math.ulp(x));

    }
}